baseURL = "https://professorseb.com/"
languageCode = "en-us"
title = "Sebastian Maniak"
theme = "bond"

[params]
  description = "Technology. Strategy. Intelligence."
  author = "Sebastian Maniak"
  youtubeChannel = "https://www.youtube.com/@professorseb"
  twitterHandle = "sebbycorp"
  linkedinURL = "https://www.linkedin.com/in/maniakseb"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 3
  [[menu.main]]
    name = "YouTube"
    url = "/youtube/"
    weight = 4
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]
